---

- name: Install passlib dependency
  apt:
    name: python-passlib
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: htpasswd - add users to password file
  htpasswd:
    "{{ item }}"
  loop: "{{ htpasswd_users }}"
